import React, { useState } from 'react';
import { Arrow, Eyebrow } from './UI.jsx';
import { team, services } from '../data/portfolio.js';

const challenges = [
  { title: 'Too many disconnected tools.', label: 'Connect the operation', note: 'Sales in one tab. Stock in another. The same information entered twice.', result: 'One workspace. A clearer working day.', description: 'Bring the handoffs, permissions, and data into a connected workflow built around your team.', skills: ['ERP / CRM', 'Odoo', 'Integrations'], project: 'erp', work: 'Construction ERP', artifact: ['Projects & sites', 'Materials & requests', 'Estimates & budgets'] },
  { title: 'An idea that needs to exist.', label: 'Build a useful product', note: 'The idea is there. The first useful version needs a shape.', result: 'From a rough idea to a working product.', description: 'Define the essential journey, design the interface, and build the system that makes it work.', skills: ['Product engineering', 'SaaS', 'Web interfaces'], project: 'affiliate', work: 'Maroc Affiliate', artifact: ['A clear user journey', 'A connected platform', 'A usable first release'] },
  { title: 'The same task. Again. And again.', label: 'Give people time back', note: 'Copying updates. Chasing statuses. Repeating the same follow-up.', result: 'Less repetition. More room to think.', description: 'Connect the repetitive steps with practical automation, keeping people in control of the decisions that matter.', skills: ['Automation', 'Integrations', 'Human review'], project: 'crm', work: 'Sales workspace', artifact: ['Capture the request', 'Prepare the next action', 'Review & move forward'] },
];

export default function AboutStudio() {
  const [personIndex, setPersonIndex] = useState(0);
  const [challengeIndex, setChallengeIndex] = useState(0);
  const person = team[personIndex], challenge = challenges[challengeIndex];
  function navigate(event, index) {
    if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return;
    event.preventDefault();
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? team.length - 1 : (index + 1) % team.length;
    setPersonIndex(next);
    document.getElementById(`person-${next}`).focus();
  }
  return <div className="studio-about page-wrap">
    <section className="studio-people" aria-labelledby="people-title">
      <div className="studio-intro"><Eyebrow>01 / The people you work with</Eyebrow><h2 id="people-title">Two minds.<br/>Your side of <em>the table.</em></h2><p>AYNKO is the software engineering practice of Aymane Chellak and Zakaria Bak. You work directly with the people shaping and building your system.</p><span className="studio-location"><span className="status-dot"/> Morocco · Working worldwide</span><p className="studio-hint">Choose a name. Get to know the practice.</p>
        <div className="people-tabs" role="tablist" aria-label="Meet the founders">{team.map((member, index) => <button key={member.email} id={`person-${index}`} role="tab" aria-selected={personIndex === index} aria-controls="person-card" tabIndex={personIndex === index ? 0 : -1} onClick={() => setPersonIndex(index)} onKeyDown={event => navigate(event, index)}><span className="person-tab-initials" aria-hidden="true">{member.name.split(' ').map(word => word[0]).join('')}</span><span>{member.name}<small>{member.role}</small></span><Arrow/></button>)}</div>
      </div>
      <div className="profile-desk"><div className="desk-label eyebrow">Independent minds / Shared craft</div><div className="profile-underlay" aria-hidden="true"/><article id="person-card" role="tabpanel" aria-labelledby={`person-${personIndex}`} tabIndex={0} className="studio-profile"><div key={personIndex} className="profile-content"><div className="profile-top"><span className="eyebrow">AYNKO / Meet the co-founder</span><span className="profile-number">0{personIndex + 1}</span></div><div className="profile-identity"><span className="profile-monogram" aria-hidden="true">{person.name.split(' ').map(word => word[0]).join('')}<i>.</i></span><h3>{person.name}</h3><p>{person.role}</p></div><div className="profile-expertise"><h4 className="eyebrow">The expertise behind our studio</h4><p>Shared capabilities we bring to your project.</p><div className="studio-skill-list">{services.flatMap(service => service.tags).map(skill => <span key={skill}>{skill}</span>)}</div></div><a className="profile-contact" href={`mailto:${person.email}`}>Talk to {person.name.split(' ')[0]}<Arrow/></a></div></article><p className="desk-footnote">A direct conversation. From first thought to final detail.</p></div>
    </section>
    <section className="studio-playground" aria-labelledby="playground-title"><div className="studio-playground-heading"><div><Eyebrow>02 / A little of how we think</Eyebrow><h2 id="playground-title">What would you<br/>bring to <em>our desk?</em></h2></div><p>Start with something familiar.<br/>Choose a challenge to see where we would begin.</p></div><div className="challenge-workspace"><div className="challenge-picker"><span className="eyebrow">Your starting point</span>{challenges.map((item, index) => <button key={item.title} aria-pressed={challengeIndex === index} aria-controls="challenge-result" onClick={() => setChallengeIndex(index)}><span className="eyebrow">0{index + 1}</span><span>{item.title}<small>{item.label}</small></span><Arrow/></button>)}<a href="/contact" className="link-action">Something else in mind? <Arrow/></a></div><div id="challenge-result" className="challenge-result" aria-live="polite" aria-atomic="true"><div key={challengeIndex} className="challenge-result-content"><div className="brief-note"><span className="eyebrow">The brief</span><p>“{challenge.note}”</p><span className="note-corner" aria-hidden="true"/></div><div className="solution-sheet"><div className="solution-top"><span className="eyebrow">Our starting point</span><span aria-hidden="true">↗</span></div><h3>{challenge.result}</h3><p>{challenge.description}</p><div className="solution-artifact">{challenge.artifact.map((line, index) => <div key={line} style={{ '--item': index }}><span aria-hidden="true">✓</span>{line}</div>)}</div><div className="studio-skill-list">{challenge.skills.map(skill => <span key={skill}>{skill}</span>)}</div><a href={`/work#${challenge.project}`} className="solution-project"><span><small>Explore related work</small>{challenge.work}</span><Arrow/></a></div></div></div></div></section>
  </div>;
}
