import sharp from "sharp";
import { mkdir, writeFile, stat } from "node:fs/promises";

const sources = {
  affiliate: "maroc-affiliate-01.png",
  erp: "odoo-02-chantier-form.png",
  materials: "odoo-03-material-request.png",
  estimate: "odoo-04-estimation.png",
  boq: "odoo-05-boq.png",
  crm: "assets/crm/leads.png",
  contacts: "assets/crm/contacts.png",
  workflows: "assets/crm/workflows.png",
  finance: "Secondo project/Secondo project/demo-dashboard.png",
  invoices: "Secondo project/Secondo project/demo-invoices.png",
  transactions: "Secondo project/Secondo project/demo-transactions.png",
  mobile: "Secondo project/Secondo project/demo-phone-overview.png",
};
await mkdir("assets/optimized", { recursive: true });
const manifest = {};
let before = 0,
  after = 0;
for (const [name, source] of Object.entries(sources)) {
  const metadata = await sharp(source).metadata();
  const widths = [
    ...new Set([Math.min(640, metadata.width), Math.min(1280, metadata.width)]),
  ];
  const variants = [];
  for (const width of widths) {
    const path = `assets/optimized/${name}-${width}.webp`;
    // Source screenshots are preserved; only generated presentation assets are resized.
    await sharp(source)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 86, effort: 6 })
      .toFile(path);
    variants.push(`${path} ${width}w`);
  }
  const src = `assets/optimized/${name}-${widths.at(-1)}.webp`;
  manifest[source] = {
    src,
    srcset: variants.join(", "),
    width: metadata.width,
    height: metadata.height,
  };
  before += (await stat(source)).size;
  after += (await stat(src)).size;
  console.log(name, metadata.width, metadata.height, (await stat(src)).size);
}
await writeFile(
  "js/image-manifest.js",
  `// Generated by npm run images. Original screenshots remain untouched.\nexport const images = ${JSON.stringify(manifest, null, 2)};\n`,
);
console.log(
  `Full-size delivery assets: ${before} → ${after} bytes (${Math.round((1 - after / before) * 100)}% smaller)`,
);
